# Generated by Django 4.2.6 on 2023-10-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidate_id_alter_position_id_alter_voter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
